package com.thoughtworks.guessnumber;

import com.thoughtworks.guessnumber.Library;
import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'sbyan' at '6/27/16 10:09 AM' with Gradle 2.13
 *
 * @author sbyan, @date 6/27/16 10:09 AM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
