package com.thoughtworks.guessnumber;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sbyan' at '6/27/16 10:09 AM' with Gradle 2.13
 *
 * @author sbyan, @date 6/27/16 10:09 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
